-- sql
CREATE TABLE IF NOT EXISTS platform_invitation (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   invitee_email VARCHAR(254) NOT NULL,
   created_by_user_id BIGINT NOT NULL,
   role VARCHAR(50) NOT NULL,
   token VARCHAR(255) NOT NULL,
   invitation_status VARCHAR(50) NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
   expires_at TIMESTAMP WITH TIME ZONE,
   confirmed_at TIMESTAMP WITH TIME ZONE
);

-- unique constraint / quick lookup by email
CREATE UNIQUE INDEX IF NOT EXISTS ux_platform_invitation_invitee_email
    ON platform_invitation (invitee_email);

-- index for token lookups (e.g. confirmation)
CREATE INDEX IF NOT EXISTS ix_platform_invitation_token
    ON platform_invitation (token);

-- index on creator for joins / queries
CREATE INDEX IF NOT EXISTS ix_platform_invitation_created_by
    ON platform_invitation (created_by_user_id);
