-- Make idempotent fixes to password_reset_token so we don't edit V5.
-- H2/PostgreSQL-compatible enough for fresh DBs.

CREATE TABLE IF NOT EXISTS password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    valid BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE password_reset_token ADD COLUMN IF NOT EXISTS token_hash VARCHAR(128);
ALTER TABLE password_reset_token ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE password_reset_token ADD COLUMN IF NOT EXISTS used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE password_reset_token ADD COLUMN IF NOT EXISTS valid BOOLEAN NOT NULL DEFAULT TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS ux_password_reset_token_token_hash
    ON password_reset_token (token_hash);

CREATE INDEX IF NOT EXISTS idx_password_reset_token_expires_at
    ON password_reset_token (expires_at);

CREATE INDEX IF NOT EXISTS idx_password_reset_token_user_id
    ON password_reset_token (user_id);